name: Generate Pacman Contribution Graph

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Corrigido aqui: especificado o repositório completo 'Platane/snk'
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            pacman-output/pacman-contribution-graph.svg?game=pacman
            pacman-output/pacman-contribution-graph-dark.svg?game=pacman&palette=github-dark

      - name: Push to pacman-output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: pacman-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
